import React from 'react';

export function HeroAurora() {
  return <section className="relative overflow-hidden bg-slate-950 px-6 py-24 text-white sm:py-32"><div className="absolute -left-24 top-0 h-72 w-72 rounded-full bg-fuchsia-500/30 blur-3xl" /><div className="absolute -right-20 bottom-0 h-80 w-80 rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative mx-auto max-w-5xl text-center"><span className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Now in public beta</span><h1 className="mt-8 text-5xl font-black tracking-tight sm:text-7xl">Turn ambitious ideas into <span className="bg-gradient-to-r from-fuchsia-400 to-cyan-300 bg-clip-text text-transparent">remarkable products.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">The collaborative workspace where strategy, design, and engineering move as one.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><button className="rounded-full bg-white px-7 py-3.5 font-bold text-slate-950">Start building free</button><button className="rounded-full border border-white/20 px-7 py-3.5 font-bold">Watch overview →</button></div><p className="mt-6 text-xs text-slate-500">No credit card · Cancel anytime</p></div></section>;
}

export function HeroEditorial() {
  return <section className="bg-[#f4efe6] px-6 py-20 text-[#222018] sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.25em] text-orange-700">Studio Journal — Issue 04</p><h1 className="mt-5 font-serif text-6xl leading-[.95] sm:text-7xl">Work with more intention.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-stone-600">A calmer way to plan projects, protect focus, and make meaningful progress—without the busywork.</p><div className="mt-9 flex items-center gap-5"><button className="bg-[#222018] px-6 py-3 text-sm font-bold text-white">Explore the method</button><a className="border-b border-stone-500 pb-1 text-sm font-bold">Read our story</a></div></div><div className="relative aspect-[4/3] overflow-hidden bg-orange-200"><div className="absolute inset-8 border border-stone-800/20" /><div className="absolute left-1/2 top-1/2 h-52 w-40 -translate-x-1/2 -translate-y-1/2 rotate-6 bg-orange-500 shadow-2xl" /><div className="absolute left-[28%] top-[28%] h-44 w-32 -rotate-12 bg-[#f8f3e9] shadow-xl"><p className="p-4 font-serif text-2xl italic">Make space for what matters.</p></div></div></div></section>;
}

export function HeroDashboard() {
  return <section className="overflow-hidden bg-white px-6 pt-20 text-slate-900 sm:pt-28"><div className="mx-auto max-w-6xl text-center"><div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />AI reports just shipped</div><h1 className="mx-auto mt-6 max-w-4xl text-5xl font-black tracking-tight sm:text-7xl">Know exactly what drives your growth.</h1><p className="mx-auto mt-6 max-w-2xl text-lg text-slate-500">One clear view of every customer, campaign, and conversion. Built for teams who move fast.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><button className="rounded-lg bg-indigo-600 px-6 py-3.5 font-bold text-white shadow-lg shadow-indigo-200">Start free trial</button><button className="rounded-lg border border-slate-200 px-6 py-3.5 font-bold">Book a demo</button></div><div className="mx-auto mt-16 max-w-5xl rounded-t-2xl border border-slate-200 bg-slate-50 p-3 shadow-2xl"><div className="rounded-xl border border-slate-200 bg-white p-5 text-left"><div className="flex gap-2"><i className="h-2.5 w-2.5 rounded-full bg-red-400" /><i className="h-2.5 w-2.5 rounded-full bg-amber-400" /><i className="h-2.5 w-2.5 rounded-full bg-emerald-400" /></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{['Revenue', '$128.4k', '+24.8%'].map((x, i) => <div key={x} className="rounded-xl border p-5"><p className="text-xs text-slate-400">{i ? 'This month' : 'Overview'}</p><p className="mt-2 text-2xl font-black">{x}</p></div>)}</div></div></div></div></section>;
}

export function HeroSplit() {
  return <section className="bg-lime-300 text-zinc-950"><div className="mx-auto grid min-h-[640px] max-w-7xl lg:grid-cols-2"><div className="flex flex-col justify-center px-6 py-20 sm:px-12"><p className="mb-6 font-mono text-sm uppercase tracking-widest">Fitness, reimagined</p><h1 className="text-6xl font-black uppercase leading-[.9] tracking-tighter sm:text-8xl">Move<br />your way.</h1><p className="mt-8 max-w-md text-lg font-medium">Adaptive training plans that learn from every rep, run, and recovery day.</p><button className="mt-9 w-fit rounded-full bg-zinc-950 px-7 py-4 font-bold text-white">Build your plan →</button></div><div className="relative min-h-[420px] overflow-hidden bg-zinc-950"><div className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full border-[40px] border-lime-300/80" /><div className="absolute left-1/2 top-1/2 h-36 w-36 -translate-x-1/2 -translate-y-1/2 rotate-45 bg-white" /><p className="absolute bottom-8 left-8 text-sm font-bold uppercase tracking-widest text-white">01 / Find your rhythm</p></div></div></section>;
}

export function HeroMinimal() {
  return <section className="bg-white px-6 py-24 sm:py-36"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[1fr_300px] lg:items-end"><h1 className="text-6xl font-medium leading-[.95] tracking-[-.06em] text-neutral-900 sm:text-8xl">Finance that finally feels <em className="font-serif font-normal text-blue-600">human.</em></h1><div><p className="text-base leading-7 text-neutral-500">Save, spend, and invest with an account designed around your life—not the other way around.</p><button className="mt-6 rounded-full bg-blue-600 px-6 py-3 font-semibold text-white">Open an account</button></div></div><div className="mt-20 grid grid-cols-2 gap-px bg-neutral-200 border border-neutral-200 sm:grid-cols-4">{[['4.8%', 'APY on savings'], ['$0', 'Monthly fees'], ['2 min', 'To get started'], ['24/7', 'Human support']].map(([a, b]) => <div className="bg-white p-6" key={b}><p className="text-3xl font-semibold">{a}</p><p className="mt-2 text-sm text-neutral-500">{b}</p></div>)}</div></div></section>;
}

export function FeaturesBento() {
  return <section className="bg-slate-950 px-6 py-24 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold text-violet-400">EVERYTHING CONNECTED</p><h2 className="mt-3 max-w-2xl text-4xl font-black sm:text-5xl">One workspace. Zero friction.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{[['md:col-span-2', '◎', 'Live collaboration', 'Build together without stepping on toes. Every cursor, comment, and change stays perfectly in sync.'], ['', '✦', 'AI copilot', 'Go from rough thought to polished work in seconds.'], ['', '⌁', 'Smart automations', 'Make repetitive work disappear.'], ['md:col-span-2', '↗', 'Insights that act', 'Turn project signals into clear next steps before blockers slow you down.']].map(([span, icon, title, desc], i) => <article key={title} className={`${span} relative min-h-64 overflow-hidden rounded-3xl border border-white/10 bg-white/[.06] p-7`}><span className="text-3xl text-violet-400">{icon}</span><div className="absolute bottom-7 left-7 right-7"><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-slate-400">{desc}</p></div>{i === 0 && <div className="absolute right-8 top-8 hidden gap-2 sm:flex"><i className="h-10 w-10 rounded-full bg-amber-400" /><i className="h-10 w-10 -translate-x-4 rounded-full bg-cyan-400" /><i className="h-10 w-10 -translate-x-8 rounded-full bg-pink-400" /></div>}</article>)}</div></div></section>;
}

export function FeaturesCards() {
  return <section className="bg-[#fffaf2] px-6 py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="font-mono text-sm text-rose-600">WHY PAPERPLANE</p><h2 className="mt-4 font-serif text-5xl text-stone-900">Designed for your best work.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[['01', 'Clarity by default', 'A calm, considered space that keeps the important work in view.'], ['02', 'Flexible foundations', 'Shape a workflow around your team, not the other way around.'], ['03', 'Made for momentum', 'Thoughtful shortcuts help you move from idea to done.']].map(([n, t, d]) => <article key={n} className="border-t border-stone-300 pt-6"><span className="font-mono text-xs text-rose-600">{n}</span><div className="my-8 flex h-20 w-20 items-center justify-center rounded-full bg-rose-100 text-3xl">{n === '01' ? '◐' : n === '02' ? '◇' : '↗'}</div><h3 className="text-xl font-bold">{t}</h3><p className="mt-3 leading-7 text-stone-600">{d}</p></article>)}</div></div></section>;
}

export function FeaturesSteps() {
  return <section className="bg-white px-6 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">How it works</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">From signup to shipped in minutes.</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-3"><div className="absolute left-[16%] right-[16%] top-7 hidden border-t-2 border-dashed border-blue-200 md:block" />{[['1', 'Connect your tools', 'Bring your data over with secure, one-click integrations.'], ['2', 'Set your workflow', 'Choose a template or make the process completely yours.'], ['3', 'Watch work flow', 'Track progress, automate handoffs, and celebrate the wins.']].map(([n, t, d]) => <div className="relative text-center" key={n}><div className="relative mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-blue-600 text-lg font-black text-white ring-8 ring-blue-50">{n}</div><h3 className="mt-7 text-xl font-bold">{t}</h3><p className="mx-auto mt-3 max-w-xs text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>;
}

export function FeaturesList() {
  return <section className="bg-zinc-100 px-6 py-24"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-2"><div><span className="rounded-full bg-zinc-900 px-3 py-1 text-xs font-bold text-white">BUILT DIFFERENT</span><h2 className="mt-6 text-5xl font-black tracking-tight">The details make the difference.</h2><p className="mt-5 text-lg leading-8 text-zinc-600">Every interaction has been considered, tested, and refined to help your team do its best work.</p><div className="mt-10 aspect-video rounded-3xl bg-gradient-to-br from-amber-300 via-orange-400 to-pink-500 p-8"><div className="h-full rounded-2xl bg-white/90 p-5 shadow-xl"><div className="h-3 w-24 rounded bg-zinc-200" /><div className="mt-6 space-y-3">{[80, 55, 68].map(x => <div key={x} className="h-8 rounded bg-zinc-100" style={{ width: `${x}%` }} />)}</div></div></div></div><div className="divide-y divide-zinc-300">{[['⌘', 'Keyboard first', 'Navigate, create, and organize without reaching for your mouse.'], ['⚡', 'Seriously fast', 'Everything responds instantly, even as your workspace grows.'], ['◉', 'Private by design', 'Enterprise-grade security built into every layer.'], ['↻', 'Always in sync', 'Pick up on any device exactly where you left off.']].map(([i, t, d]) => <div key={t} className="flex gap-5 py-7"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white text-xl shadow-sm">{i}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-zinc-600">{d}</p></div></div>)}</div></div></section>;
}

export function PricingSimple() {
  return <section className="bg-white px-6 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><h2 className="text-4xl font-black">Simple pricing. No surprises.</h2><p className="mt-4 text-slate-500">Start free, upgrade when you need to.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Starter', '$0', 'For side projects and small ideas.', '1 workspace,Up to 3 members,1 GB storage'], ['Pro', '$18', 'For teams ready to move faster.', 'Unlimited workspaces,Unlimited members,100 GB storage'], ['Scale', '$49', 'For growing organizations.', 'Advanced permissions,SAML SSO,Priority support']].map(([name, price, desc, items], i) => <article key={name} className={`rounded-2xl border p-7 ${i === 1 ? 'border-indigo-600 bg-indigo-600 text-white shadow-xl' : 'border-slate-200'}`}><div className="flex justify-between"><h3 className="font-bold">{name}</h3>{i === 1 && <span className="rounded-full bg-white/20 px-3 py-1 text-xs">POPULAR</span>}</div><p className="mt-5"><span className="text-5xl font-black">{price}</span><span className={i === 1 ? 'text-indigo-200' : 'text-slate-400'}>/month</span></p><p className={`mt-4 text-sm ${i === 1 ? 'text-indigo-100' : 'text-slate-500'}`}>{desc}</p><button className={`mt-7 w-full rounded-lg py-3 font-bold ${i === 1 ? 'bg-white text-indigo-600' : 'bg-slate-950 text-white'}`}>Choose {name}</button><ul className="mt-7 space-y-3 text-sm">{items.split(',').map(x => <li key={x}>✓ &nbsp;{x}</li>)}</ul></article>)}</div></div></section>;
}

export function PricingDark() {
  return <section className="bg-neutral-950 px-6 py-24 text-white"><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-lime-400">PRICING</p><h2 className="mt-3 text-5xl font-black">Pick your pace.</h2></div><p className="max-w-sm text-neutral-400">Every plan includes unlimited projects and a 14-day trial.</p></div><div className="mt-14 overflow-hidden rounded-3xl border border-white/15"><div className="grid md:grid-cols-2"><article className="p-8 sm:p-10"><h3 className="text-2xl font-bold">Independent</h3><p className="mt-5 text-5xl font-black">$12<span className="text-base font-normal text-neutral-500"> / month</span></p><p className="mt-5 text-neutral-400">Everything you need to run your work.</p><button className="mt-8 w-full rounded-full border border-white/30 py-3 font-bold">Start free</button></article><article className="bg-lime-300 p-8 text-neutral-950 sm:p-10"><h3 className="text-2xl font-bold">Studio</h3><p className="mt-5 text-5xl font-black">$29<span className="text-base font-normal text-neutral-600"> / member</span></p><p className="mt-5 text-neutral-700">Powerful collaboration for ambitious teams.</p><button className="mt-8 w-full rounded-full bg-neutral-950 py-3 font-bold text-white">Start free</button></article></div><div className="grid border-t border-white/15 p-8 text-sm text-neutral-300 sm:grid-cols-3 sm:p-10">{['Unlimited projects', 'Version history', 'Export everything'].map(x => <p className="py-2" key={x}>✦ {x}</p>)}</div></div></div></section>;
}

export function PricingComparison() {
  return <section className="bg-sky-50 px-6 py-24"><div className="mx-auto max-w-6xl"><h2 className="text-center text-4xl font-black text-slate-900">A plan for every stage</h2><div className="mt-12 overflow-x-auto rounded-2xl bg-white shadow-sm"><div className="min-w-[720px]"><div className="grid grid-cols-4 border-b p-6"><div /><div className="font-bold">Free</div><div className="font-bold text-blue-600">Business</div><div className="font-bold">Enterprise</div></div>{[['Monthly price', '$0', '$24', 'Custom'], ['Team members', '3', 'Unlimited', 'Unlimited'], ['Automations', '100/mo', '10,000/mo', 'Unlimited'], ['Analytics', 'Basic', 'Advanced', 'Custom'], ['Support', 'Community', 'Priority', 'Dedicated']].map((row, i) => <div key={row[0]} className={`grid grid-cols-4 p-5 text-sm ${i % 2 ? 'bg-slate-50' : ''}`}>{row.map((x, j) => <div key={x} className={j ? 'text-center' : 'font-semibold'}>{x}</div>)}</div>)}<div className="grid grid-cols-4 gap-4 p-6"><div /><button className="rounded-lg border py-3 font-bold">Get started</button><button className="rounded-lg bg-blue-600 py-3 font-bold text-white">Try free</button><button className="rounded-lg bg-slate-900 py-3 font-bold text-white">Contact us</button></div></div></div></div></section>;
}

export function PricingToggle() {
  return <section className="bg-[#f7f5ff] px-6 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><h2 className="text-5xl font-black tracking-tight">Invest in momentum.</h2><div className="mt-7 inline-flex rounded-full bg-white p-1 shadow-sm"><button className="rounded-full bg-violet-600 px-5 py-2 text-sm font-bold text-white">Yearly · save 20%</button><button className="px-5 py-2 text-sm font-bold text-slate-500">Monthly</button></div></div><div className="mt-12 grid overflow-hidden rounded-3xl border border-violet-100 bg-white lg:grid-cols-3">{[['Launch', '9', 'For getting started'], ['Grow', '19', 'For scaling teams'], ['Lead', '39', 'For complex work']].map(([t, p, d], i) => <article key={t} className={`p-8 ${i < 2 ? 'border-b lg:border-b-0 lg:border-r' : ''}`}><div className="flex items-center justify-between"><h3 className="text-xl font-bold">{t}</h3>{i === 1 && <span className="rounded-full bg-violet-100 px-2 py-1 text-xs font-bold text-violet-700">BEST VALUE</span>}</div><p className="mt-2 text-sm text-slate-500">{d}</p><p className="mt-8 text-5xl font-black">${p}<span className="text-sm font-normal text-slate-400">/mo</span></p><button className={`mt-8 w-full rounded-xl py-3 font-bold ${i === 1 ? 'bg-violet-600 text-white' : 'bg-violet-50 text-violet-700'}`}>Start 14-day trial</button><ul className="mt-7 space-y-3 text-sm text-slate-600"><li>✓ Unlimited projects</li><li>✓ Collaboration tools</li><li>✓ Detailed reporting</li></ul></article>)}</div></div></section>;
}

export function TestimonialsSpotlight() {
  return <section className="bg-amber-300 px-6 py-24"><div className="mx-auto max-w-5xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-neutral-900 text-2xl text-white">“</div><blockquote className="mt-9 text-4xl font-black leading-tight tracking-tight sm:text-6xl">“It’s rare for a tool to change not just how you work, but how you think about the work.”</blockquote><div className="mt-10"><div className="mx-auto h-12 w-12 rounded-full bg-gradient-to-br from-rose-400 to-violet-600" /><p className="mt-3 font-bold">Maya Chen</p><p className="text-sm text-neutral-700">VP of Product at Northstar</p></div></div></section>;
}

export function TestimonialsGrid() {
  return <section className="bg-white px-6 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-bold text-emerald-600">LOVED BY 12,000+ TEAMS</p><h2 className="mt-3 text-4xl font-black">Don’t take our word for it.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['“Our weekly planning went from two hours to twenty minutes.”', 'Jamie R.', 'Operations, Loomly'], ['“The first product our entire team actually enjoys using.”', 'Ari S.', 'Founder, Arcade'], ['“We finally have one source of truth—and it stays up to date.”', 'Noah K.', 'Design, Monogram']].map(([q, n, r], i) => <article key={n} className={`rounded-2xl p-7 ${i === 1 ? 'bg-emerald-600 text-white' : 'bg-slate-50'}`}><div className="text-amber-400">★★★★★</div><blockquote className="mt-6 text-xl font-semibold leading-8">{q}</blockquote><div className="mt-8 flex items-center gap-3"><div className={`h-10 w-10 rounded-full ${i === 0 ? 'bg-pink-300' : i === 1 ? 'bg-yellow-300' : 'bg-blue-300'}`} /><div><p className="text-sm font-bold">{n}</p><p className={`text-xs ${i === 1 ? 'text-emerald-100' : 'text-slate-500'}`}>{r}</p></div></div></article>)}</div></div></section>;
}

export function TestimonialsWall() {
  return <section className="overflow-hidden bg-slate-950 px-6 py-24 text-white"><div className="mx-auto max-w-6xl"><h2 className="max-w-xl text-4xl font-black">Built with our customers, every step of the way.</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['“A genuine game-changer.”', 'Elena, CEO'], ['“Fast, focused, delightful.”', 'Marcus, Design'], ['“We shipped 2x faster.”', 'Priya, Product'], ['“Support is phenomenal.”', 'Theo, Founder']].map(([q, n], i) => <article key={n} className={`rounded-2xl border border-white/10 bg-white/[.06] p-6 ${i % 2 ? 'lg:translate-y-8' : ''}`}><p className="text-lg font-semibold leading-7">{q}</p><div className="mt-8 flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-gradient-to-br from-cyan-300 to-violet-500" /><p className="text-xs text-slate-400">{n}</p></div></article>)}</div></div></section>;
}

export function FAQAccordion() {
  return <section className="bg-white px-6 py-24"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-sm font-bold text-indigo-600">FAQ</p><h2 className="mt-3 text-4xl font-black">Questions, answered.</h2></div><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{[['Can I try it before I pay?', 'Absolutely. Every plan starts with a 14-day free trial, with no credit card required.'], ['Can I change plans later?', 'Yes. Upgrade, downgrade, or cancel at any time from your workspace settings.'], ['Is my data secure?', 'We use encryption in transit and at rest, regular audits, and strict access controls.'], ['Do you offer discounts?', 'We offer special pricing for nonprofits, educators, and early-stage startups.']].map(([q, a], i) => <details key={q} className="group py-6" open={i === 0}><summary className="flex cursor-pointer list-none items-center justify-between font-bold">{q}<span className="text-xl group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-500">{a}</p></details>)}</div></div></section>;
}

export function FAQSplit() {
  return <section className="bg-[#f2f0eb] px-6 py-24"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-sm text-orange-700">GOOD TO KNOW</p><h2 className="mt-4 font-serif text-5xl">A few things you might be wondering.</h2><p className="mt-5 text-stone-600">Still curious? <a className="font-bold underline">Talk to our team.</a></p></div><div className="grid gap-x-10 gap-y-9 sm:grid-cols-2">{[['What happens after the trial?', 'Choose a plan that fits or export your data—no pressure.'], ['Can I invite guests?', 'Yes, guest access is included on every paid plan.'], ['Does it work offline?', 'Our desktop and mobile apps support offline editing.'], ['Where is data hosted?', 'Choose US or EU data residency for your workspace.'], ['Do you have an API?', 'A complete REST API is available to all customers.'], ['Can you help us migrate?', 'Our team provides guided migration for larger teams.']].map(([q, a], i) => <article key={q} className="border-t border-stone-400 pt-4"><span className="font-mono text-xs text-orange-700">0{i + 1}</span><h3 className="mt-3 font-bold">{q}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{a}</p></article>)}</div></div></section>;
}

export function FAQDark() {
  return <section className="bg-zinc-950 px-6 py-24 text-white"><div className="mx-auto max-w-5xl"><div className="grid gap-12 lg:grid-cols-3"><div><h2 className="text-4xl font-black">Need to know.</h2><p className="mt-4 text-zinc-400">Quick answers to the questions we hear most.</p><button className="mt-6 rounded-full bg-lime-300 px-5 py-2.5 text-sm font-bold text-zinc-950">Ask us anything</button></div><div className="space-y-3 lg:col-span-2">{[['Is there a free plan?', 'Yes—free forever for individuals.'], ['How quickly can we set up?', 'Most teams are up and running in under an hour.'], ['Can we use our own domain?', 'Custom domains are included with Pro and Business.'], ['What support do you provide?', 'Email support for all, plus live chat on paid plans.']].map(([q, a]) => <details key={q} className="group rounded-xl border border-white/10 bg-white/5 p-5"><summary className="flex cursor-pointer list-none justify-between font-bold">{q}<span className="text-lime-300">↓</span></summary><p className="mt-3 text-sm text-zinc-400">{a}</p></details>)}</div></div></div></section>;
}

export function CTAGradient() {
  return <section className="bg-white px-6 py-20"><div className="relative mx-auto max-w-6xl overflow-hidden rounded-[2rem] bg-gradient-to-br from-violet-600 via-fuchsia-600 to-orange-400 px-7 py-16 text-center text-white sm:px-14 sm:py-20"><div className="absolute -left-10 -top-20 h-52 w-52 rounded-full border-[30px] border-white/10" /><div className="absolute -bottom-20 -right-8 h-64 w-64 rounded-full border-[40px] border-white/10" /><h2 className="relative text-4xl font-black sm:text-6xl">Make your next move.</h2><p className="relative mx-auto mt-5 max-w-xl text-white/80">Join thousands of teams turning their best ideas into their best work.</p><div className="relative mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button className="rounded-full bg-white px-7 py-3.5 font-bold text-violet-700">Start for free</button><button className="rounded-full border border-white/40 px-7 py-3.5 font-bold">Talk to sales</button></div></div></section>;
}

export function CTAInline() {
  return <section className="bg-lime-300 px-6 py-16"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="font-mono text-sm uppercase tracking-wider">Ready when you are</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Bring your boldest idea.</h2></div><form className="flex w-full max-w-lg flex-col gap-3 sm:flex-row"><input aria-label="Work email" className="min-w-0 flex-1 rounded-full border-2 border-zinc-950 bg-transparent px-5 py-3 placeholder:text-zinc-700" placeholder="Work email" /><button className="rounded-full bg-zinc-950 px-6 py-3 font-bold text-white">Get early access</button></form></div></section>;
}

export function CTAMinimal() {
  return <section className="bg-neutral-950 px-6 py-24 text-white"><div className="mx-auto max-w-5xl border-y border-white/15 py-16 text-center"><p className="text-sm uppercase tracking-[.3em] text-neutral-500">Your next chapter</p><h2 className="mt-6 font-serif text-5xl italic sm:text-7xl">Let’s make something matter.</h2><button className="mt-9 rounded-none border-b-2 border-white pb-2 text-lg font-bold">Begin a conversation →</button></div></section>;
}

export function FooterMega() {
  return <footer className="bg-slate-950 px-6 pb-8 pt-16 text-white"><div className="mx-auto max-w-6xl"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="sm:col-span-2"><p className="text-2xl font-black">orbit°</p><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">Tools for modern teams doing work that matters.</p><div className="mt-6 flex gap-3"><span>◉</span><span>◈</span><span>◍</span></div></div>{[['Product', 'Overview,Features,Solutions,Changelog'], ['Company', 'About,Careers,Press,Partners'], ['Resources', 'Blog,Guides,Help center,API docs']].map(([h, links]) => <div key={h}><h3 className="text-sm font-bold">{h}</h3><ul className="mt-4 space-y-3 text-sm text-slate-400">{links.split(',').map(x => <li key={x}><a>{x}</a></li>)}</ul></div>)}</div><div className="mt-14 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-xs text-slate-500 sm:flex-row"><p>© 2026 Orbit Labs, Inc.</p><div className="flex gap-5"><a>Privacy</a><a>Terms</a><a>Cookies</a></div></div></div></footer>;
}

export function FooterNewsletter() {
  return <footer className="bg-[#eee9df] px-6 py-16 text-stone-900"><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-2"><div><p className="font-serif text-4xl italic">Sunday</p><h2 className="mt-8 max-w-md text-3xl font-bold">A thoughtful note on work and life, once a week.</h2><form className="mt-6 flex max-w-md border-b border-stone-700"><input className="min-w-0 flex-1 bg-transparent py-3 outline-none" placeholder="you@example.com" /><button className="font-bold">Subscribe →</button></form></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{[['Explore', 'Journal,Studio,Notes'], ['Follow', 'Instagram,LinkedIn,Are.na'], ['Legal', 'Privacy,Terms,Contact']].map(([h, l]) => <div key={h}><h3 className="text-xs font-bold uppercase tracking-widest">{h}</h3><ul className="mt-5 space-y-3 text-sm text-stone-600">{l.split(',').map(x => <li key={x}>{x}</li>)}</ul></div>)}</div></div><p className="mt-16 border-t border-stone-300 pt-6 text-xs text-stone-500">Made slowly, with care. © 2026 Sunday Studio.</p></div></footer>;
}

export function FooterCompact() {
  return <footer className="bg-white px-6 py-10"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 border-t border-slate-200 pt-8 sm:flex-row"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-600 font-black text-white">N</span><span className="font-black">North</span></div><nav className="flex flex-wrap justify-center gap-6 text-sm text-slate-500"><a>Product</a><a>Pricing</a><a>About</a><a>Blog</a></nav><p className="text-xs text-slate-400">© 2026 North, Inc.</p></div></footer>;
}

export function NavbarClassic() {
  return <header className="bg-white px-6 py-4"><nav className="mx-auto flex max-w-6xl items-center justify-between"><a className="flex items-center gap-2 text-xl font-black"><span className="h-7 w-7 rounded-lg bg-indigo-600" />Linearize</a><div className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a>Product</a><a>Solutions</a><a>Resources</a><a>Pricing</a></div><div className="flex items-center gap-3"><button className="hidden text-sm font-bold sm:block">Sign in</button><button className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Get started</button></div></nav></header>;
}

export function NavbarCentered() {
  return <header className="bg-[#f5f0e7] px-6 py-5"><nav className="mx-auto grid max-w-6xl grid-cols-2 items-center md:grid-cols-3"><div className="hidden gap-6 text-sm md:flex"><a>Shop</a><a>Stories</a><a>About</a></div><a className="font-serif text-2xl font-bold md:text-center">maison.</a><div className="flex justify-end gap-5 text-sm"><a className="hidden sm:block">Search</a><a>Bag (0)</a></div></nav></header>;
}

export function NavbarPill() {
  return <header className="bg-sky-100 px-4 py-5"><nav className="mx-auto flex max-w-5xl items-center justify-between rounded-full border border-white/80 bg-white/70 px-5 py-3 shadow-sm backdrop-blur"><a className="flex items-center gap-2 font-black text-sky-950"><span className="text-sky-500">✦</span> skyward</a><div className="hidden gap-6 text-sm text-sky-950 md:flex"><a>Platform</a><a>Customers</a><a>Pricing</a></div><button className="rounded-full bg-sky-950 px-4 py-2 text-xs font-bold text-white">Join waitlist</button></nav></header>;
}

export function LogoCloudMono() {
  return <section className="bg-white px-6 py-16"><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-slate-400">Powering teams at</p><div className="mt-10 grid grid-cols-2 items-center gap-8 text-xl font-black text-slate-400 sm:grid-cols-3 lg:grid-cols-6">{['ACME', 'NORTH°', 'Vertex', 'Capsule', 'SPECTRA', 'Horizon'].map((x, i) => <div key={x} className={i % 2 ? 'font-serif italic' : 'tracking-tight'}>{x}</div>)}</div></div></section>;
}

export function LogoCloudCards() {
  return <section className="bg-slate-950 px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><h2 className="max-w-xl text-3xl font-black">Trusted by builders shaping what’s next.</h2><p className="text-sm text-slate-400">From 2-person startups to global teams.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{['◇ Aperture', '✦ Layers', '◉ Motif', '⌁ Afterglow', '△ Peak', '○ Form'].map(x => <div key={x} className="flex h-24 items-center justify-center rounded-xl border border-white/10 bg-white/5 font-bold text-slate-300">{x}</div>)}</div></div></section>;
}
