export interface HeroAuroraProps { className?: string; }
export function HeroAurora({ className = '' }: HeroAuroraProps = {}) {
  return <section className={`relative overflow-hidden bg-inverse px-6 py-24 text-on-brand sm:py-32 ${className}`}><div className="absolute -left-24 top-0 h-72 w-72 rounded-full bg-accent/30 blur-3xl" /><div className="absolute -right-20 bottom-0 h-80 w-80 rounded-full bg-accent/20 blur-3xl" /><div className="relative mx-auto max-w-5xl text-center"><span className="rounded-full border border-inverse-line/15 bg-surface/5 px-4 py-2 text-xs font-semibold uppercase tracking-[.2em] text-accent">Now in public beta</span><h1 className="mt-8 text-5xl font-black tracking-tight sm:text-7xl">Turn ambitious ideas into <span className="bg-gradient-to-r from-brand to-accent bg-clip-text text-transparent">remarkable products.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-inverse-muted">The collaborative workspace where strategy, design, and engineering move as one.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" className="rounded-full bg-surface px-7 py-3.5 font-bold text-ink">Start building free</button><button type="button" className="rounded-full border border-inverse-line/20 px-7 py-3.5 font-bold">Watch overview →</button></div><p className="mt-6 text-xs text-muted">No credit card · Cancel anytime</p></div></section>;
}

export interface HeroEditorialProps { className?: string; }
export function HeroEditorial({ className = '' }: HeroEditorialProps = {}) {
  return <section className={`bg-canvas px-6 py-20 text-ink sm:py-28 ${className}`}><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.25em] text-accent">Studio Journal — Issue 04</p><h1 className="mt-5 font-serif text-6xl leading-[.95] sm:text-7xl">Work with more intention.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-muted">A calmer way to plan projects, protect focus, and make meaningful progress—without the busywork.</p><div className="mt-9 flex items-center gap-5"><button type="button" className="bg-inverse px-6 py-3 text-sm font-bold text-on-brand">Explore the method</button><a href="#" className="border-b border-line pb-1 text-sm font-bold">Read our story</a></div></div><div className="relative aspect-[4/3] overflow-hidden bg-accent-soft"><div className="absolute inset-8 border border-line/20" /><div className="absolute left-1/2 top-1/2 h-52 w-40 -translate-x-1/2 -translate-y-1/2 rotate-6 bg-accent shadow-2xl" /><div className="absolute left-[28%] top-[28%] h-44 w-32 -rotate-12 bg-surface shadow-xl"><p className="p-4 font-serif text-2xl italic">Make space for what matters.</p></div></div></div></section>;
}

export interface HeroDashboardProps { className?: string; }
export function HeroDashboard({ className = '' }: HeroDashboardProps = {}) {
  return <section className={`overflow-hidden bg-surface px-6 pt-20 text-ink sm:pt-28 ${className}`}><div className="mx-auto max-w-6xl text-center"><div className="inline-flex items-center gap-2 rounded-full bg-brand-soft px-3 py-1 text-xs font-bold text-brand-strong"><span className="h-2 w-2 rounded-full bg-brand" />AI reports just shipped</div><h1 className="mx-auto mt-6 max-w-4xl text-5xl font-black tracking-tight sm:text-7xl">Know exactly what drives your growth.</h1><p className="mx-auto mt-6 max-w-2xl text-lg text-muted">One clear view of every customer, campaign, and conversion. Built for teams who move fast.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" className="rounded-lg bg-brand px-6 py-3.5 font-bold text-on-brand shadow-lg shadow-brand-soft">Start free trial</button><button type="button" className="rounded-lg border border-line px-6 py-3.5 font-bold">Book a demo</button></div><div className="mx-auto mt-16 max-w-5xl rounded-t-2xl border border-line bg-surface-muted p-3 shadow-2xl"><div className="rounded-xl border border-line bg-surface p-5 text-left"><div className="flex gap-2"><i className="h-2.5 w-2.5 rounded-full bg-accent" /><i className="h-2.5 w-2.5 rounded-full bg-accent" /><i className="h-2.5 w-2.5 rounded-full bg-brand" /></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{['Revenue', '$128.4k', '+24.8%'].map((x, i) => <div key={x} className="rounded-xl border p-5"><p className="text-xs text-subtle">{i ? 'This month' : 'Overview'}</p><p className="mt-2 text-2xl font-black">{x}</p></div>)}</div></div></div></div></section>;
}

export interface HeroSplitProps { className?: string; }
export function HeroSplit({ className = '' }: HeroSplitProps = {}) {
  return <section className={`bg-brand text-ink ${className}`}><div className="mx-auto grid min-h-[640px] max-w-7xl lg:grid-cols-2"><div className="flex flex-col justify-center px-6 py-20 sm:px-12"><p className="mb-6 font-mono text-sm uppercase tracking-widest">Fitness, reimagined</p><h1 className="text-6xl font-black uppercase leading-[.9] tracking-tighter sm:text-8xl">Move<br />your way.</h1><p className="mt-8 max-w-md text-lg font-medium">Adaptive training plans that learn from every rep, run, and recovery day.</p><button type="button" className="mt-9 w-fit rounded-full bg-inverse px-7 py-4 font-bold text-on-brand">Build your plan →</button></div><div className="relative min-h-[420px] overflow-hidden bg-inverse"><div className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full border-[40px] border-accent/80" /><div className="absolute left-1/2 top-1/2 h-36 w-36 -translate-x-1/2 -translate-y-1/2 rotate-45 bg-surface" /><p className="absolute bottom-8 left-8 text-sm font-bold uppercase tracking-widest text-on-brand">01 / Find your rhythm</p></div></div></section>;
}

export interface HeroMinimalProps { className?: string; }
export function HeroMinimal({ className = '' }: HeroMinimalProps = {}) {
  return <section className={`bg-surface px-6 py-24 sm:py-36 ${className}`}><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[1fr_300px] lg:items-end"><h1 className="text-6xl font-medium leading-[.95] tracking-[-.06em] text-ink sm:text-8xl">Finance that finally feels <em className="font-serif font-normal text-brand">human.</em></h1><div><p className="text-base leading-7 text-muted">Save, spend, and invest with an account designed around your life—not the other way around.</p><button type="button" className="mt-6 rounded-full bg-brand px-6 py-3 font-semibold text-on-brand">Open an account</button></div></div><div className="mt-20 grid grid-cols-2 gap-px bg-line border border-line sm:grid-cols-4">{[['4.8%', 'APY on savings'], ['$0', 'Monthly fees'], ['2 min', 'To get started'], ['24/7', 'Human support']].map(([a, b]) => <div className="bg-surface p-6" key={b}><p className="text-3xl font-semibold">{a}</p><p className="mt-2 text-sm text-muted">{b}</p></div>)}</div></div></section>;
}

export interface FeaturesBentoProps { className?: string; }
export function FeaturesBento({ className = '' }: FeaturesBentoProps = {}) {
  return <section className={`bg-inverse px-6 py-24 text-on-brand ${className}`}><div className="mx-auto max-w-6xl"><p className="text-sm font-bold text-accent">EVERYTHING CONNECTED</p><h2 className="mt-3 max-w-2xl text-4xl font-black sm:text-5xl">One workspace. Zero friction.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{[['md:col-span-2', '◎', 'Live collaboration', 'Build together without stepping on toes. Every cursor, comment, and change stays perfectly in sync.'], ['', '✦', 'AI copilot', 'Go from rough thought to polished work in seconds.'], ['', '⌁', 'Smart automations', 'Make repetitive work disappear.'], ['md:col-span-2', '↗', 'Insights that act', 'Turn project signals into clear next steps before blockers slow you down.']].map(([span, icon, title, desc], i) => <article key={title} className={`${span} relative min-h-64 overflow-hidden rounded-3xl border border-inverse-line/10 bg-surface/5 p-7`}><span className="text-3xl text-accent">{icon}</span><div className="absolute bottom-7 left-7 right-7"><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-subtle">{desc}</p></div>{i === 0 && <div className="absolute right-8 top-8 hidden gap-2 sm:flex"><i className="h-10 w-10 rounded-full bg-accent" /><i className="h-10 w-10 -translate-x-4 rounded-full bg-accent" /><i className="h-10 w-10 -translate-x-8 rounded-full bg-accent" /></div>}</article>)}</div></div></section>;
}

export interface FeaturesCardsProps { className?: string; }
export function FeaturesCards({ className = '' }: FeaturesCardsProps = {}) {
  return <section className={`bg-canvas px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="font-mono text-sm text-accent">WHY PAPERPLANE</p><h2 className="mt-4 font-serif text-5xl text-ink">Designed for your best work.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[['01', 'Clarity by default', 'A calm, considered space that keeps the important work in view.'], ['02', 'Flexible foundations', 'Shape a workflow around your team, not the other way around.'], ['03', 'Made for momentum', 'Thoughtful shortcuts help you move from idea to done.']].map(([n, t, d]) => <article key={n} className="border-t border-line pt-6"><span className="font-mono text-xs text-accent">{n}</span><div className="my-8 flex h-20 w-20 items-center justify-center rounded-full bg-accent-soft text-3xl">{n === '01' ? '◐' : n === '02' ? '◇' : '↗'}</div><h3 className="text-xl font-bold">{t}</h3><p className="mt-3 leading-7 text-muted">{d}</p></article>)}</div></div></section>;
}

export interface FeaturesStepsProps { className?: string; }
export function FeaturesSteps({ className = '' }: FeaturesStepsProps = {}) {
  return <section className={`bg-surface px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-brand">How it works</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">From signup to shipped in minutes.</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-3"><div className="absolute left-[16%] right-[16%] top-7 hidden border-t-2 border-dashed border-brand-soft md:block" />{[['1', 'Connect your tools', 'Bring your data over with secure, one-click integrations.'], ['2', 'Set your workflow', 'Choose a template or make the process completely yours.'], ['3', 'Watch work flow', 'Track progress, automate handoffs, and celebrate the wins.']].map(([n, t, d]) => <div className="relative text-center" key={n}><div className="relative mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-brand text-lg font-black text-on-brand ring-8 ring-brand-soft">{n}</div><h3 className="mt-7 text-xl font-bold">{t}</h3><p className="mx-auto mt-3 max-w-xs text-sm leading-6 text-muted">{d}</p></div>)}</div></div></section>;
}

export interface FeaturesListProps { className?: string; }
export function FeaturesList({ className = '' }: FeaturesListProps = {}) {
  return <section className={`bg-surface-muted px-6 py-24 ${className}`}><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-2"><div><span className="rounded-full bg-inverse px-3 py-1 text-xs font-bold text-on-brand">BUILT DIFFERENT</span><h2 className="mt-6 text-5xl font-black tracking-tight">The details make the difference.</h2><p className="mt-5 text-lg leading-8 text-muted">Every interaction has been considered, tested, and refined to help your team do its best work.</p><div className="mt-10 aspect-video rounded-3xl bg-gradient-to-br from-accent via-accent to-accent p-8"><div className="h-full rounded-2xl bg-surface/90 p-5 shadow-xl"><div className="h-3 w-24 rounded bg-line" /><div className="mt-6 space-y-3">{[80, 55, 68].map(x => <div key={x} className="h-8 rounded bg-surface-muted" style={{ width: `${x}%` }} />)}</div></div></div></div><div className="divide-y divide-zinc-300">{[['⌘', 'Keyboard first', 'Navigate, create, and organize without reaching for your mouse.'], ['⚡', 'Seriously fast', 'Everything responds instantly, even as your workspace grows.'], ['◉', 'Private by design', 'Enterprise-grade security built into every layer.'], ['↻', 'Always in sync', 'Pick up on any device exactly where you left off.']].map(([i, t, d]) => <div key={t} className="flex gap-5 py-7"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-surface text-xl shadow-sm">{i}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-muted">{d}</p></div></div>)}</div></div></section>;
}

export interface PricingSimpleProps { className?: string; }
export function PricingSimple({ className = '' }: PricingSimpleProps = {}) {
  return <section className={`bg-surface px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><div className="text-center"><h2 className="text-4xl font-black">Simple pricing. No surprises.</h2><p className="mt-4 text-muted">Start free, upgrade when you need to.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Starter', '$0', 'For side projects and small ideas.', '1 workspace,Up to 3 members,1 GB storage'], ['Pro', '$18', 'For teams ready to move faster.', 'Unlimited workspaces,Unlimited members,100 GB storage'], ['Scale', '$49', 'For growing organizations.', 'Advanced permissions,SAML SSO,Priority support']].map(([name, price, desc, items], i) => <article key={name} className={`rounded-2xl border p-7 ${i === 1 ? 'border-brand bg-brand text-on-brand shadow-xl' : 'border-line'}`}><div className="flex justify-between"><h3 className="font-bold">{name}</h3>{i === 1 && <span className="rounded-full bg-surface/20 px-3 py-1 text-xs">POPULAR</span>}</div><p className="mt-5"><span className="text-5xl font-black">{price}</span><span className={i === 1 ? 'text-on-brand/80' : 'text-subtle'}>/month</span></p><p className={`mt-4 text-sm ${i === 1 ? 'text-on-brand/80' : 'text-muted'}`}>{desc}</p><button type="button" className={`mt-7 w-full rounded-lg py-3 font-bold ${i === 1 ? 'bg-surface text-brand' : 'bg-inverse text-on-brand'}`}>Choose {name}</button><ul className="mt-7 space-y-3 text-sm">{items.split(',').map(x => <li key={x}>✓ &nbsp;{x}</li>)}</ul></article>)}</div></div></section>;
}

export interface PricingDarkProps { className?: string; }
export function PricingDark({ className = '' }: PricingDarkProps = {}) {
  return <section className={`bg-inverse px-6 py-24 text-on-brand ${className}`}><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-accent">PRICING</p><h2 className="mt-3 text-5xl font-black">Pick your pace.</h2></div><p className="max-w-sm text-inverse-muted">Every plan includes unlimited projects and a 14-day trial.</p></div><div className="mt-14 overflow-hidden rounded-3xl border border-inverse-line/15"><div className="grid md:grid-cols-2"><article className="p-8 sm:p-10"><h3 className="text-2xl font-bold">Independent</h3><p className="mt-5 text-5xl font-black">$12<span className="text-base font-normal text-muted"> / month</span></p><p className="mt-5 text-inverse-muted">Everything you need to run your work.</p><button type="button" className="mt-8 w-full rounded-full border border-inverse-line/30 py-3 font-bold">Start free</button></article><article className="bg-brand p-8 text-ink sm:p-10"><h3 className="text-2xl font-bold">Studio</h3><p className="mt-5 text-5xl font-black">$29<span className="text-base font-normal text-muted"> / member</span></p><p className="mt-5 text-muted">Powerful collaboration for ambitious teams.</p><button type="button" className="mt-8 w-full rounded-full bg-inverse py-3 font-bold text-on-brand">Start free</button></article></div><div className="grid border-t border-inverse-line/15 p-8 text-sm text-inverse-muted sm:grid-cols-3 sm:p-10">{['Unlimited projects', 'Version history', 'Export everything'].map(x => <p className="py-2" key={x}>✦ {x}</p>)}</div></div></div></section>;
}

export interface PricingComparisonProps { className?: string; }
export function PricingComparison({ className = '' }: PricingComparisonProps = {}) {
  return <section className={`bg-surface-muted px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><h2 className="text-center text-4xl font-black text-ink">A plan for every stage</h2><div className="mt-12 overflow-x-auto rounded-2xl bg-surface shadow-sm"><div className="min-w-[720px]"><div className="grid grid-cols-4 border-b p-6"><div /><div className="font-bold">Free</div><div className="font-bold text-brand">Business</div><div className="font-bold">Enterprise</div></div>{[['Monthly price', '$0', '$24', 'Custom'], ['Team members', '3', 'Unlimited', 'Unlimited'], ['Automations', '100/mo', '10,000/mo', 'Unlimited'], ['Analytics', 'Basic', 'Advanced', 'Custom'], ['Support', 'Community', 'Priority', 'Dedicated']].map((row, i) => <div key={row[0]} className={`grid grid-cols-4 p-5 text-sm ${i % 2 ? 'bg-surface-muted' : ''}`}>{row.map((x, j) => <div key={x} className={j ? 'text-center' : 'font-semibold'}>{x}</div>)}</div>)}<div className="grid grid-cols-4 gap-4 p-6"><div /><button type="button" className="rounded-lg border py-3 font-bold">Get started</button><button type="button" className="rounded-lg bg-brand py-3 font-bold text-on-brand">Try free</button><button type="button" className="rounded-lg bg-inverse py-3 font-bold text-on-brand">Contact us</button></div></div></div></div></section>;
}

export interface PricingToggleProps { className?: string; }
export function PricingToggle({ className = '' }: PricingToggleProps = {}) {
  return <section className={`bg-canvas px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><div className="text-center"><h2 className="text-5xl font-black tracking-tight">Invest in momentum.</h2><div className="mt-7 inline-flex rounded-full bg-surface p-1 shadow-sm"><button type="button" className="rounded-full bg-brand px-5 py-2 text-sm font-bold text-on-brand">Yearly · save 20%</button><button type="button" className="px-5 py-2 text-sm font-bold text-muted">Monthly</button></div></div><div className="mt-12 grid overflow-hidden rounded-3xl border border-brand-soft bg-surface lg:grid-cols-3">{[['Launch', '9', 'For getting started'], ['Grow', '19', 'For scaling teams'], ['Lead', '39', 'For complex work']].map(([t, p, d], i) => <article key={t} className={`p-8 ${i < 2 ? 'border-b lg:border-b-0 lg:border-r' : ''}`}><div className="flex items-center justify-between"><h3 className="text-xl font-bold">{t}</h3>{i === 1 && <span className="rounded-full bg-brand-soft px-2 py-1 text-xs font-bold text-brand-strong">BEST VALUE</span>}</div><p className="mt-2 text-sm text-muted">{d}</p><p className="mt-8 text-5xl font-black">${p}<span className="text-sm font-normal text-subtle">/mo</span></p><button type="button" className={`mt-8 w-full rounded-xl py-3 font-bold ${i === 1 ? 'bg-brand text-on-brand' : 'bg-brand-soft text-brand-strong'}`}>Start 14-day trial</button><ul className="mt-7 space-y-3 text-sm text-muted"><li>✓ Unlimited projects</li><li>✓ Collaboration tools</li><li>✓ Detailed reporting</li></ul></article>)}</div></div></section>;
}

export interface TestimonialsSpotlightProps { className?: string; }
export function TestimonialsSpotlight({ className = '' }: TestimonialsSpotlightProps = {}) {
  return <section className={`bg-accent px-6 py-24 ${className}`}><div className="mx-auto max-w-5xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-inverse text-2xl text-on-brand">“</div><blockquote className="mt-9 text-4xl font-black leading-tight tracking-tight sm:text-6xl">“It’s rare for a tool to change not just how you work, but how you think about the work.”</blockquote><div className="mt-10"><div className="mx-auto h-12 w-12 rounded-full bg-gradient-to-br from-brand to-accent" /><p className="mt-3 font-bold">Maya Chen</p><p className="text-sm text-muted">VP of Product at Northstar</p></div></div></section>;
}

export interface TestimonialsGridProps { className?: string; }
export function TestimonialsGrid({ className = '' }: TestimonialsGridProps = {}) {
  return <section className={`bg-surface px-6 py-24 ${className}`}><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-bold text-brand">LOVED BY 12,000+ TEAMS</p><h2 className="mt-3 text-4xl font-black">Don’t take our word for it.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['“Our weekly planning went from two hours to twenty minutes.”', 'Jamie R.', 'Operations, Loomly'], ['“The first product our entire team actually enjoys using.”', 'Ari S.', 'Founder, Arcade'], ['“We finally have one source of truth—and it stays up to date.”', 'Noah K.', 'Design, Monogram']].map(([q, n, r], i) => <article key={n} className={`rounded-2xl p-7 ${i === 1 ? 'bg-brand text-on-brand' : 'bg-surface-muted'}`}><div className="text-accent">★★★★★</div><blockquote className="mt-6 text-xl font-semibold leading-8">{q}</blockquote><div className="mt-8 flex items-center gap-3"><div className={`h-10 w-10 rounded-full ${i === 0 ? 'bg-accent' : i === 1 ? 'bg-accent' : 'bg-accent'}`} /><div><p className="text-sm font-bold">{n}</p><p className={`text-xs ${i === 1 ? 'text-on-brand/80' : 'text-muted'}`}>{r}</p></div></div></article>)}</div></div></section>;
}

export interface TestimonialsWallProps { className?: string; }
export function TestimonialsWall({ className = '' }: TestimonialsWallProps = {}) {
  return <section className={`overflow-hidden bg-inverse px-6 py-24 text-on-brand ${className}`}><div className="mx-auto max-w-6xl"><h2 className="max-w-xl text-4xl font-black">Built with our customers, every step of the way.</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['“A genuine game-changer.”', 'Elena, CEO'], ['“Fast, focused, delightful.”', 'Marcus, Design'], ['“We shipped 2x faster.”', 'Priya, Product'], ['“Support is phenomenal.”', 'Theo, Founder']].map(([q, n], i) => <article key={n} className={`rounded-2xl border border-inverse-line/10 bg-surface/5 p-6 ${i % 2 ? 'lg:translate-y-8' : ''}`}><p className="text-lg font-semibold leading-7">{q}</p><div className="mt-8 flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-gradient-to-br from-brand to-accent" /><p className="text-xs text-subtle">{n}</p></div></article>)}</div></div></section>;
}

export interface FAQAccordionProps { className?: string; }
export function FAQAccordion({ className = '' }: FAQAccordionProps = {}) {
  return <section className={`bg-surface px-6 py-24 ${className}`}><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-sm font-bold text-brand">FAQ</p><h2 className="mt-3 text-4xl font-black">Questions, answered.</h2></div><div className="mt-12 divide-y divide-slate-200 border-y border-line">{[['Can I try it before I pay?', 'Absolutely. Every plan starts with a 14-day free trial, with no credit card required.'], ['Can I change plans later?', 'Yes. Upgrade, downgrade, or cancel at any time from your workspace settings.'], ['Is my data secure?', 'We use encryption in transit and at rest, regular audits, and strict access controls.'], ['Do you offer discounts?', 'We offer special pricing for nonprofits, educators, and early-stage startups.']].map(([q, a], i) => <details key={q} className="group py-6" open={i === 0}><summary className="flex cursor-pointer list-none items-center justify-between font-bold">{q}<span className="text-xl group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-6 text-muted">{a}</p></details>)}</div></div></section>;
}

export interface FAQSplitProps { className?: string; }
export function FAQSplit({ className = '' }: FAQSplitProps = {}) {
  return <section className={`bg-canvas px-6 py-24 ${className}`}><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-sm text-accent">GOOD TO KNOW</p><h2 className="mt-4 font-serif text-5xl">A few things you might be wondering.</h2><p className="mt-5 text-muted">Still curious? <a href="#" className="font-bold underline">Talk to our team.</a></p></div><div className="grid gap-x-10 gap-y-9 sm:grid-cols-2">{[['What happens after the trial?', 'Choose a plan that fits or export your data—no pressure.'], ['Can I invite guests?', 'Yes, guest access is included on every paid plan.'], ['Does it work offline?', 'Our desktop and mobile apps support offline editing.'], ['Where is data hosted?', 'Choose US or EU data residency for your workspace.'], ['Do you have an API?', 'A complete REST API is available to all customers.'], ['Can you help us migrate?', 'Our team provides guided migration for larger teams.']].map(([q, a], i) => <article key={q} className="border-t border-line pt-4"><span className="font-mono text-xs text-accent">0{i + 1}</span><h3 className="mt-3 font-bold">{q}</h3><p className="mt-2 text-sm leading-6 text-muted">{a}</p></article>)}</div></div></section>;
}

export interface FAQDarkProps { className?: string; }
export function FAQDark({ className = '' }: FAQDarkProps = {}) {
  return <section className={`bg-inverse px-6 py-24 text-on-brand ${className}`}><div className="mx-auto max-w-5xl"><div className="grid gap-12 lg:grid-cols-3"><div><h2 className="text-4xl font-black">Need to know.</h2><p className="mt-4 text-subtle">Quick answers to the questions we hear most.</p><button type="button" className="mt-6 rounded-full bg-brand px-5 py-2.5 text-sm font-bold text-ink">Ask us anything</button></div><div className="space-y-3 lg:col-span-2">{[['Is there a free plan?', 'Yes—free forever for individuals.'], ['How quickly can we set up?', 'Most teams are up and running in under an hour.'], ['Can we use our own domain?', 'Custom domains are included with Pro and Business.'], ['What support do you provide?', 'Email support for all, plus live chat on paid plans.']].map(([q, a]) => <details key={q} className="group rounded-xl border border-inverse-line/10 bg-surface/5 p-5"><summary className="flex cursor-pointer list-none justify-between font-bold">{q}<span className="text-accent">↓</span></summary><p className="mt-3 text-sm text-subtle">{a}</p></details>)}</div></div></div></section>;
}

export interface CTAGradientProps { className?: string; }
export function CTAGradient({ className = '' }: CTAGradientProps = {}) {
  return <section className={`bg-surface px-6 py-20 ${className}`}><div className="relative mx-auto max-w-6xl overflow-hidden rounded-[2rem] bg-gradient-to-br from-brand via-accent to-accent px-7 py-16 text-center text-on-brand sm:px-14 sm:py-20"><div className="absolute -left-10 -top-20 h-52 w-52 rounded-full border-[30px] border-inverse-line/10" /><div className="absolute -bottom-20 -right-8 h-64 w-64 rounded-full border-[40px] border-inverse-line/10" /><h2 className="relative text-4xl font-black sm:text-6xl">Make your next move.</h2><p className="relative mx-auto mt-5 max-w-xl text-on-brand/80">Join thousands of teams turning their best ideas into their best work.</p><div className="relative mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" className="rounded-full bg-surface px-7 py-3.5 font-bold text-brand-strong">Start for free</button><button type="button" className="rounded-full border border-inverse-line/40 px-7 py-3.5 font-bold">Talk to sales</button></div></div></section>;
}

export interface CTAInlineProps { className?: string; }
export function CTAInline({ className = '' }: CTAInlineProps = {}) {
  return <section className={`bg-brand px-6 py-16 ${className}`}><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="font-mono text-sm uppercase tracking-wider">Ready when you are</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Bring your boldest idea.</h2></div><form className="flex w-full max-w-lg flex-col gap-3 sm:flex-row"><input type="email" aria-label="Work email" className="min-w-0 flex-1 rounded-full border-2 border-ink bg-transparent px-5 py-3 placeholder:text-muted" placeholder="Work email" /><button type="submit" className="rounded-full bg-inverse px-6 py-3 font-bold text-on-brand">Get early access</button></form></div></section>;
}

export interface CTAMinimalProps { className?: string; }
export function CTAMinimal({ className = '' }: CTAMinimalProps = {}) {
  return <section className={`bg-inverse px-6 py-24 text-on-brand ${className}`}><div className="mx-auto max-w-5xl border-y border-inverse-line/15 py-16 text-center"><p className="text-sm uppercase tracking-[.3em] text-muted">Your next chapter</p><h2 className="mt-6 font-serif text-5xl italic sm:text-7xl">Let’s make something matter.</h2><button type="button" className="mt-9 rounded-none border-b-2 border-inverse-line pb-2 text-lg font-bold">Begin a conversation →</button></div></section>;
}

export interface FooterMegaProps { className?: string; }
export function FooterMega({ className = '' }: FooterMegaProps = {}) {
  return <footer className={`bg-inverse px-6 pb-8 pt-16 text-on-brand ${className}`}><div className="mx-auto max-w-6xl"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="sm:col-span-2"><p className="text-2xl font-black">orbit°</p><p className="mt-4 max-w-xs text-sm leading-6 text-subtle">Tools for modern teams doing work that matters.</p><div className="mt-6 flex gap-3"><span>◉</span><span>◈</span><span>◍</span></div></div>{[['Product', 'Overview,Features,Solutions,Changelog'], ['Company', 'About,Careers,Press,Partners'], ['Resources', 'Blog,Guides,Help center,API docs']].map(([h, links]) => <div key={h}><h3 className="text-sm font-bold">{h}</h3><ul className="mt-4 space-y-3 text-sm text-subtle">{links.split(',').map(x => <li key={x}><a href="#">{x}</a></li>)}</ul></div>)}</div><div className="mt-14 flex flex-col justify-between gap-4 border-t border-inverse-line/10 pt-6 text-xs text-muted sm:flex-row"><p>© 2026 Orbit Labs, Inc.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Cookies</a></div></div></div></footer>;
}

export interface FooterNewsletterProps { className?: string; }
export function FooterNewsletter({ className = '' }: FooterNewsletterProps = {}) {
  return <footer className={`bg-surface-muted px-6 py-16 text-ink ${className}`}><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-2"><div><p className="font-serif text-4xl italic">Sunday</p><h2 className="mt-8 max-w-md text-3xl font-bold">A thoughtful note on work and life, once a week.</h2><form className="mt-6 flex max-w-md border-b border-line"><input type="email" aria-label="Email address" className="min-w-0 flex-1 bg-transparent py-3 outline-none" placeholder="you@example.com" /><button type="submit" className="font-bold">Subscribe →</button></form></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{[['Explore', 'Journal,Studio,Notes'], ['Follow', 'Instagram,LinkedIn,Are.na'], ['Legal', 'Privacy,Terms,Contact']].map(([h, l]) => <div key={h}><h3 className="text-xs font-bold uppercase tracking-widest">{h}</h3><ul className="mt-5 space-y-3 text-sm text-muted">{l.split(',').map(x => <li key={x}>{x}</li>)}</ul></div>)}</div></div><p className="mt-16 border-t border-line pt-6 text-xs text-muted">Made slowly, with care. © 2026 Sunday Studio.</p></div></footer>;
}

export interface FooterCompactProps { className?: string; }
export function FooterCompact({ className = '' }: FooterCompactProps = {}) {
  return <footer className={`bg-surface px-6 py-10 ${className}`}><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 border-t border-line pt-8 sm:flex-row"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand font-black text-on-brand">N</span><span className="font-black">North</span></div><nav className="flex flex-wrap justify-center gap-6 text-sm text-muted"><a href="#">Product</a><a href="#">Pricing</a><a href="#">About</a><a href="#">Blog</a></nav><p className="text-xs text-subtle">© 2026 North, Inc.</p></div></footer>;
}

export interface NavbarClassicProps { className?: string; }
export function NavbarClassic({ className = '' }: NavbarClassicProps = {}) {
  return <header className={`bg-surface px-6 py-4 ${className}`}><nav className="mx-auto flex max-w-6xl items-center justify-between"><a href="#" className="flex items-center gap-2 text-xl font-black"><span className="h-7 w-7 rounded-lg bg-brand" />Linearize</a><div className="hidden items-center gap-7 text-sm font-medium text-muted md:flex"><a href="#">Product</a><a href="#">Solutions</a><a href="#">Resources</a><a href="#">Pricing</a></div><div className="flex items-center gap-3"><button type="button" className="hidden text-sm font-bold sm:block">Sign in</button><button type="button" className="rounded-lg bg-inverse px-4 py-2.5 text-sm font-bold text-on-brand">Get started</button></div></nav></header>;
}

export interface NavbarCenteredProps { className?: string; }
export function NavbarCentered({ className = '' }: NavbarCenteredProps = {}) {
  return <header className={`bg-canvas px-6 py-5 ${className}`}><nav className="mx-auto grid max-w-6xl grid-cols-2 items-center md:grid-cols-3"><div className="hidden gap-6 text-sm md:flex"><a href="#">Shop</a><a href="#">Stories</a><a href="#">About</a></div><a href="#" className="font-serif text-2xl font-bold md:text-center">maison.</a><div className="flex justify-end gap-5 text-sm"><a href="#" className="hidden sm:block">Search</a><a href="#">Bag (0)</a></div></nav></header>;
}

export interface NavbarPillProps { className?: string; }
export function NavbarPill({ className = '' }: NavbarPillProps = {}) {
  return <header className={`bg-brand-soft px-4 py-5 ${className}`}><nav className="mx-auto flex max-w-5xl items-center justify-between rounded-full border border-inverse-line/80 bg-surface/70 px-5 py-3 shadow-sm backdrop-blur"><a href="#" className="flex items-center gap-2 font-black text-ink"><span className="text-brand">✦</span> skyward</a><div className="hidden gap-6 text-sm text-ink md:flex"><a href="#">Platform</a><a href="#">Customers</a><a href="#">Pricing</a></div><button type="button" className="rounded-full bg-inverse px-4 py-2 text-xs font-bold text-on-brand">Join waitlist</button></nav></header>;
}

export interface LogoCloudMonoProps { className?: string; }
export function LogoCloudMono({ className = '' }: LogoCloudMonoProps = {}) {
  return <section className={`bg-surface px-6 py-16 ${className}`}><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-subtle">Powering teams at</p><div className="mt-10 grid grid-cols-2 items-center gap-8 text-xl font-black text-subtle sm:grid-cols-3 lg:grid-cols-6">{['ACME', 'NORTH°', 'Vertex', 'Capsule', 'SPECTRA', 'Horizon'].map((x, i) => <div key={x} className={i % 2 ? 'font-serif italic' : 'tracking-tight'}>{x}</div>)}</div></div></section>;
}

export interface LogoCloudCardsProps { className?: string; }
export function LogoCloudCards({ className = '' }: LogoCloudCardsProps = {}) {
  return <section className={`bg-inverse px-6 py-20 text-on-brand ${className}`}><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><h2 className="max-w-xl text-3xl font-black">Trusted by builders shaping what’s next.</h2><p className="text-sm text-subtle">From 2-person startups to global teams.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{['◇ Aperture', '✦ Layers', '◉ Motif', '⌁ Afterglow', '△ Peak', '○ Form'].map(x => <div key={x} className="flex h-24 items-center justify-center rounded-xl border border-inverse-line/10 bg-surface/5 font-bold text-inverse-muted">{x}</div>)}</div></div></section>;
}
